import { Badge, Card, Group, Select, Stack, Text, TextInput } from "@mantine/core";
import { useState } from "react";
import { useStockMovements } from "../../hooks/useInventory";

export default function StockMovementHistory() {
  const [search, setSearch] = useState(""); const [type, setType] = useState<string | null>(null);
  const { data, isLoading } = useStockMovements({ search: search || undefined, movement_type: type || undefined, page: 1, page_size: 20 });
  return <Card withBorder radius="md"><Stack><Group justify="space-between"><Stack gap={0}><Text fw={700}>Recent stock movements</Text><Text size="sm" c="dimmed">Immutable stock history. {data?.total ?? 0} record(s).</Text></Stack></Group><Group grow><TextInput placeholder="Search product..." value={search} onChange={(event) => setSearch(event.currentTarget.value)} /><Select placeholder="All movement types" clearable value={type} onChange={setType} data={["OPENING_BALANCE", "SUPPLIER_RECEIPT", "MANUAL_INCREASE", "MANUAL_DECREASE", "ORDER_DEDUCTION", "CANCELLATION_RESTORATION"]} /></Group>{isLoading ? <Text c="dimmed">Loading stock history...</Text> : !data?.items.length ? <Text c="dimmed">No stock movements match these filters yet.</Text> : data.items.map((item) => <Group key={item.id} justify="space-between" wrap="nowrap"><Stack gap={1}><Text fw={600}>{item.product_name}</Text><Text size="xs" c="dimmed">{item.reason ?? item.movement_type.replaceAll("_", " ")} · {new Date(item.created_at).toLocaleString("en-MY", { timeZone: "Asia/Kuala_Lumpur", dateStyle: "medium", timeStyle: "short" })}</Text></Stack><Stack gap={2} align="flex-end"><Badge color={item.quantity_change < 0 ? "red" : "green"} variant="light">{item.quantity_change > 0 ? "+" : ""}{item.quantity_change} units</Badge><Text size="xs" c="dimmed">{item.quantity_before} → {item.quantity_after}</Text></Stack></Group>)}</Stack></Card>;
}
