import { Button, Group, NumberInput, Select, Stack, Text, TextInput, Textarea } from "@mantine/core";
import { useEffect } from "react";
import { useForm } from "@mantine/form";
import { notifications } from "@mantine/notifications";
import { useQuery } from "@tanstack/react-query";
import api from "../../api/axios";
import { modals } from "@mantine/modals";
import { getApiError } from "../../api/errors";
import useAuth from "../../auth/useAuth";
import { useCreateStockMovement, useOpeningBalance, useUpdateInventory } from "../../hooks/useInventory";
import type { Inventory } from "../../types/inventory";
import { FormModal } from "../common/DataTable";

export default function StockAdjustmentModal({ opened, onClose, inventory }: { opened: boolean; onClose: () => void; inventory: Inventory | null }) {
  const { admin } = useAuth();
  const movement = useCreateStockMovement(); const threshold = useUpdateInventory(); const opening = useOpeningBalance();
  const suppliers = useQuery({ queryKey: ["supplier-options"], queryFn: async () => (await api.get<Array<{id:number;name:string}>>("/inventories/supplier-options")).data, enabled: opened });
  const form = useForm({ initialValues: { movement_type: "SUPPLIER_RECEIPT", quantity: 1, reason: "", supplier_id: "", reference: "", low_stock_threshold: 10 }, validate: { quantity: (value) => value < 1 ? "Enter at least one unit" : null, reason: (value, values) => values.movement_type === "MANUAL_DECREASE" && value.trim().length < 2 ? "Explain why stock is being reduced" : null } });
  useEffect(() => { if (inventory) form.setFieldValue("low_stock_threshold", inventory.low_stock_threshold); }, [inventory, form]);
  const close = () => { if (!movement.isPending && !threshold.isPending && !opening.isPending) { form.reset(); onClose(); } };
  const submit = async () => { if (!inventory || form.validate().hasErrors) return; try { const sign = form.values.movement_type === "MANUAL_DECREASE" ? -1 : 1; await movement.mutateAsync({ inventoryId: inventory.id, data: { movement_type: form.values.movement_type as "SUPPLIER_RECEIPT" | "MANUAL_INCREASE" | "MANUAL_DECREASE", quantity_change: sign * Number(form.values.quantity), reason: form.values.reason.trim() || null, supplier_id: form.values.supplier_id ? Number(form.values.supplier_id) : null, low_stock_threshold: form.values.low_stock_threshold, reference: form.values.reference.trim() || null } }); notifications.show({ title: "Stock movement recorded", message: `${inventory.product_name} now has updated stock.`, color: "green" }); close(); } catch (error) { const apiError = getApiError(error); form.setErrors(apiError.fieldErrors); notifications.show({ title: "Unable to record stock", message: apiError.message, color: "red" }); } };
  const recordOpening = async () => { if (!inventory || !form.values.reason.trim()) { form.setFieldError("reason", "Enter a note confirming this opening balance"); return; } try { await opening.mutateAsync({ inventoryId: inventory.id, reason: form.values.reason.trim() }); notifications.show({ title: "Opening balance recorded", message: "Future stock movements are now traceable.", color: "green" }); } catch (error) { notifications.show({ title: "Unable to record opening balance", message: getApiError(error).message, color: "red" }); } };
  return <FormModal opened={opened} onClose={close} title="Record stock movement" description={inventory ? `${inventory.product_name}: ${inventory.quantity} units currently in stock.` : undefined} submitLabel="Record movement" loading={movement.isPending || threshold.isPending} isDirty={form.isDirty()} onSubmit={() => { if (form.validate().hasErrors) return; if (form.values.movement_type === "MANUAL_DECREASE") modals.openConfirmModal({ title: "Confirm stock reduction", children: <Text>Remove {form.values.quantity} units from {inventory?.product_name}?</Text>, labels: { confirm: "Reduce stock", cancel: "Go back" }, confirmProps: { color: "red" }, onConfirm: submit }); else void submit(); }}><Stack><Select label="Movement" data={[{ value: "SUPPLIER_RECEIPT", label: "Receive supplier stock" }, { value: "MANUAL_INCREASE", label: "Manual increase" }, { value: "MANUAL_DECREASE", label: "Manual decrease" }]} {...form.getInputProps("movement_type")} /><NumberInput label="Units" min={1} allowDecimal={false} {...form.getInputProps("quantity")} /><Textarea label={form.values.movement_type === "MANUAL_DECREASE" ? "Reason" : "Reason (optional)"} {...form.getInputProps("reason")} /><Select label="Supplier (optional)" data={(suppliers.data ?? []).map((item) => ({ value: String(item.id), label: item.name }))} searchable clearable {...form.getInputProps("supplier_id")} /><TextInput label="Reference (optional)" placeholder="Delivery note or internal reference" {...form.getInputProps("reference")} /><NumberInput label="Low-stock threshold" min={0} allowDecimal={false} {...form.getInputProps("low_stock_threshold")} /><Button variant="subtle" loading={threshold.isPending} disabled={!inventory || form.values.low_stock_threshold === inventory.low_stock_threshold || movement.isPending} onClick={async () => { if (!inventory) return; try { await threshold.mutateAsync({ inventoryId: inventory.id, data: { low_stock_threshold: form.values.low_stock_threshold } }); notifications.show({ title: "Threshold saved", message: "No stock quantity changed.", color: "green" }); } catch (error) { notifications.show({ title: "Unable to save threshold", message: getApiError(error).message, color: "red" }); } }}>Save threshold only</Button>{admin?.role === "OWNER" && <><Text size="sm" fw={600}>Existing stock</Text><Group><Button variant="light" color="gray" onClick={recordOpening} loading={opening.isPending}>Record current quantity as opening balance</Button><Text size="xs" c="dimmed">Enter a reason above first. This can be done once per product.</Text></Group></>}</Stack></FormModal>;
}
