export const cartCopy = {
  en: {
    cart: "Cart", add: "Add to cart", added: "Added to cart", addedShort: "Added", unavailable: "Currently unavailable",
    title: "Your cart",
    empty: "Your cart is empty.", emptyBody: "Add products to see them here.", browse: "Browse products",
    quantity: "Quantity", decrease: "Decrease quantity", increase: "Increase quantity", quantityUpdated: "Quantity updated to", quantityRange: "Enter a quantity from 1 to", remove: "Remove", removed: "Removed from cart", clear: "Clear cart", cleared: "Cart cleared", clearConfirm: "Clear every item from your cart?",
    loading: "Checking current prices and availability…", error: "We couldn’t refresh your cart.", retry: "Try again",
    noLongerAvailable: "This product is no longer available.", quantityUnavailable: "That quantity is not currently available. Reduce it to continue.",
    priceChanged: "Price updated", subtotal: "Subtotal", discount: "Discount", total: "Total",
    orderSummary: "Order summary",
    // Awaiting Umar's and the client's approval before public launch.
    orderOnWhatsApp: "Send order on WhatsApp", whatsAppNote: "WhatsApp opens with your order filled in. Send the message and we’ll confirm your order with you there.",
    orderingClosed: "Online ordering isn’t available yet.",
    orderGreeting: "Hello Bahulu Berry Cameron, I’d like to order:",
    checkout: "Checkout preview",
    checkoutTitle: "Checkout preview", checkoutIntro: "A review-only look at the future checkout. No order or payment will be created.",
    fictional: "Fictional review only", fictionalBody: "Do not enter or share real customer information in this preview.",
    fulfilment: "Fulfilment", fulfilmentBody: "Pickup, delivery coverage and charges are awaiting client approval.",
    payment: "Payment", paymentBody: "No payment provider has been selected. Payment is unavailable and test-only.",
    noSubmission: "Review complete. Ordering and payment are disabled.", backCart: "Back to cart",
  },
  ms: {
    cart: "Troli", add: "Tambah ke troli", added: "Ditambah ke troli", addedShort: "Ditambah", unavailable: "Tidak tersedia buat masa ini",
    title: "Troli anda",
    empty: "Troli anda kosong.", emptyBody: "Tambah produk untuk melihatnya di sini.", browse: "Lihat produk",
    quantity: "Kuantiti", decrease: "Kurangkan kuantiti", increase: "Tambah kuantiti", quantityUpdated: "Kuantiti dikemas kini kepada", quantityRange: "Masukkan kuantiti dari 1 hingga", remove: "Buang", removed: "Dibuang daripada troli", clear: "Kosongkan troli", cleared: "Troli dikosongkan", clearConfirm: "Kosongkan semua produk daripada troli?",
    loading: "Menyemak harga dan ketersediaan semasa…", error: "Kami tidak dapat menyegarkan troli anda.", retry: "Cuba lagi",
    noLongerAvailable: "Produk ini tidak lagi tersedia.", quantityUnavailable: "Kuantiti itu tidak tersedia sekarang. Kurangkan kuantiti untuk meneruskan.",
    priceChanged: "Harga dikemas kini", subtotal: "Jumlah kecil", discount: "Diskaun", total: "Jumlah",
    orderSummary: "Ringkasan pesanan",
    // Menunggu kelulusan Umar dan pelanggan sebelum dilancarkan kepada umum.
    orderOnWhatsApp: "Hantar pesanan di WhatsApp", whatsAppNote: "WhatsApp akan dibuka dengan pesanan anda. Hantar mesej itu dan kami akan mengesahkan pesanan anda di sana.",
    orderingClosed: "Pesanan dalam talian belum tersedia.",
    orderGreeting: "Hai Bahulu Berry Cameron, saya ingin membuat pesanan:",
    checkout: "Pratonton daftar keluar",
    checkoutTitle: "Pratonton daftar keluar", checkoutIntro: "Paparan semakan sahaja untuk daftar keluar akan datang. Tiada pesanan atau pembayaran akan dibuat.",
    fictional: "Semakan fiksyen sahaja", fictionalBody: "Jangan masukkan atau kongsi maklumat pelanggan sebenar dalam pratonton ini.",
    fulfilment: "Pemenuhan", fulfilmentBody: "Ambil sendiri, liputan penghantaran dan caj masih menunggu kelulusan pelanggan.",
    payment: "Pembayaran", paymentBody: "Tiada penyedia pembayaran dipilih. Pembayaran tidak tersedia dan untuk ujian sahaja.",
    noSubmission: "Semakan selesai. Pesanan dan pembayaran dinyahaktifkan.", backCart: "Kembali ke troli",
  },
} as const;
