export const cartCopy = {
  en: {
    cart: "Cart", add: "Add to cart", added: "Added to cart", addedShort: "Added", unavailable: "Currently unavailable",
    title: "Your cart",
    empty: "Your cart is empty.", emptyBody: "Add products to see them here.", browse: "Browse products",
    quantity: "Quantity", decrease: "Decrease quantity", increase: "Increase quantity", quantityUpdated: "Quantity updated to", quantityRange: "Enter a quantity from 1 to", remove: "Remove", removed: "Removed from cart", clear: "Clear cart", cleared: "Cart cleared", clearConfirm: "Clear every item from your cart?",
    loading: "Checking current prices and availability…", error: "We couldn’t refresh your cart.", retry: "Try again",
    noLongerAvailable: "This product is no longer available.", quantityUnavailable: "That quantity is not currently available. Reduce it to continue.",
    priceChanged: "Price updated", subtotal: "Subtotal", discount: "Discount", total: "Total",
    orderSummary: "Order summary",
    // Awaiting Umar's and the client's approval before public launch.
    orderOnWhatsApp: "Send order on WhatsApp", whatsAppNote: "WhatsApp opens with your order filled in. Send the message and we’ll confirm your order with you there.",
    orderingClosed: "Online ordering isn’t available yet.",
    orderGreeting: "Hello Bahulu Berry Cameron, I’d like to order:",
    checkout: "Pay online",
    previewTitle: "Checkout preview", previewIntro: "A review-only look at the future checkout. No order or payment will be created.",
    checkoutTitle: "Checkout", checkoutIntro: "Enter your details, then pay securely on the next page.",
    testMode: "Test mode", testModeBody: "Payments use Stripe test cards and no real money is taken. Delivery charges and terms are not set yet. Do not enter real customer details.",
    yourDetails: "Your details", deliveryAddress: "Delivery address",
    fullName: "Full name", phone: "Phone number", phoneHint: "Malaysian number such as 012-345 6789, or start with + for other countries.",
    email: "Email (optional)", emailHint: "We send your payment receipt here.",
    address: "Street address", city: "Town or city", state: "State", statePlaceholder: "Choose a state", postcode: "Postcode",
    privacy: "I agree that Bahulu Berry Cameron may use these details to process and deliver this order.",
    payNow: "Continue to payment", paying: "Opening secure payment…",
    errorSummary: "Please check the highlighted fields.",
    fieldRequired: "Please fill this in.", nameInvalid: "Enter your full name.", phoneInvalid: "Use a number such as 012-345 6789, or start with + for other countries.",
    emailInvalid: "Enter a valid email address.", addressInvalid: "Enter your street address.", postcodeInvalid: "Enter a 5-digit postcode.", privacyRequired: "Tick this box to continue.", privacyShort: "Privacy agreement",
    failUnavailable: "Some items are no longer available. Please review your cart.", failChanged: "Your order changed after it was sent. Please try again.",
    failClosed: "This checkout has finished. Please start again from your cart.", failContact: "We couldn’t place this order online. Please message us on WhatsApp.",
    failPayment: "Online payment is unavailable right now. Please try again shortly.", failInvalid: "Please check your details and try again.",
    failBusy: "Too many attempts. Please wait a few minutes and try again.", failNetwork: "We couldn’t reach checkout. Please try again.",
    successTitle: "Thank you!", successBody: "We’re confirming your payment with our payment provider.", orderNumber: "Order number",
    successHelp: "Keep this number for reference. If you have questions, message us on WhatsApp.", continueShopping: "Continue shopping",
    cancelTitle: "Payment not completed", cancelBody: "Nothing was charged. Your cart is still saved, so you can try again when you’re ready.", backToCheckout: "Return to checkout",
    fictional: "Fictional review only", fictionalBody: "Do not enter or share real customer information in this preview.",
    fulfilment: "Fulfilment", fulfilmentBody: "Pickup, delivery coverage and charges are awaiting client approval.",
    payment: "Payment", paymentBody: "No payment provider has been selected. Payment is unavailable and test-only.",
    noSubmission: "Review complete. Ordering and payment are disabled.", backCart: "Back to cart",
    item: "item", items: "items", itemColumn: "Item", each: "each", removeItem: "Remove",
    reviewPay: "Review and pay", continueToAddress: "Continue to delivery address", continueToReview: "Continue to review",
    edit: "Edit", step: "Step", stepDone: "completed", contactFor: "Contact", deliverTo: "Deliver to", noEmail: "No email given",
  },
  ms: {
    cart: "Troli", add: "Tambah ke troli", added: "Ditambah ke troli", addedShort: "Ditambah", unavailable: "Tidak tersedia buat masa ini",
    title: "Troli anda",
    empty: "Troli anda kosong.", emptyBody: "Tambah produk untuk melihatnya di sini.", browse: "Lihat produk",
    quantity: "Kuantiti", decrease: "Kurangkan kuantiti", increase: "Tambah kuantiti", quantityUpdated: "Kuantiti dikemas kini kepada", quantityRange: "Masukkan kuantiti dari 1 hingga", remove: "Buang", removed: "Dibuang daripada troli", clear: "Kosongkan troli", cleared: "Troli dikosongkan", clearConfirm: "Kosongkan semua produk daripada troli?",
    loading: "Menyemak harga dan ketersediaan semasa…", error: "Kami tidak dapat menyegarkan troli anda.", retry: "Cuba lagi",
    noLongerAvailable: "Produk ini tidak lagi tersedia.", quantityUnavailable: "Kuantiti itu tidak tersedia sekarang. Kurangkan kuantiti untuk meneruskan.",
    priceChanged: "Harga dikemas kini", subtotal: "Jumlah kecil", discount: "Diskaun", total: "Jumlah",
    orderSummary: "Ringkasan pesanan",
    // Menunggu kelulusan Umar dan pelanggan sebelum dilancarkan kepada umum.
    orderOnWhatsApp: "Hantar pesanan di WhatsApp", whatsAppNote: "WhatsApp akan dibuka dengan pesanan anda. Hantar mesej itu dan kami akan mengesahkan pesanan anda di sana.",
    orderingClosed: "Pesanan dalam talian belum tersedia.",
    orderGreeting: "Hai Bahulu Berry Cameron, saya ingin membuat pesanan:",
    checkout: "Bayar dalam talian",
    previewTitle: "Pratonton daftar keluar", previewIntro: "Paparan semakan sahaja untuk daftar keluar akan datang. Tiada pesanan atau pembayaran akan dibuat.",
    checkoutTitle: "Daftar keluar", checkoutIntro: "Masukkan butiran anda, kemudian bayar dengan selamat di halaman seterusnya.",
    testMode: "Mod ujian", testModeBody: "Pembayaran menggunakan kad ujian Stripe dan tiada wang sebenar diambil. Caj dan terma penghantaran belum ditetapkan. Jangan masukkan butiran pelanggan sebenar.",
    yourDetails: "Butiran anda", deliveryAddress: "Alamat penghantaran",
    fullName: "Nama penuh", phone: "Nombor telefon", phoneHint: "Nombor Malaysia seperti 012-345 6789, atau mulakan dengan + untuk negara lain.",
    email: "E-mel (pilihan)", emailHint: "Resit pembayaran anda dihantar ke sini.",
    address: "Alamat jalan", city: "Bandar", state: "Negeri", statePlaceholder: "Pilih negeri", postcode: "Poskod",
    privacy: "Saya bersetuju Bahulu Berry Cameron menggunakan butiran ini untuk memproses dan menghantar pesanan ini.",
    payNow: "Teruskan ke pembayaran", paying: "Membuka pembayaran selamat…",
    errorSummary: "Sila semak ruangan yang ditanda.",
    fieldRequired: "Sila isi ruangan ini.", nameInvalid: "Masukkan nama penuh anda.", phoneInvalid: "Gunakan nombor seperti 012-345 6789, atau mulakan dengan + untuk negara lain.",
    emailInvalid: "Masukkan alamat e-mel yang sah.", addressInvalid: "Masukkan alamat jalan anda.", postcodeInvalid: "Masukkan poskod 5 digit.", privacyRequired: "Tandakan kotak ini untuk meneruskan.", privacyShort: "Persetujuan privasi",
    failUnavailable: "Sesetengah produk tidak lagi tersedia. Sila semak troli anda.", failChanged: "Pesanan anda berubah selepas dihantar. Sila cuba lagi.",
    failClosed: "Daftar keluar ini telah tamat. Sila mula semula dari troli anda.", failContact: "Kami tidak dapat membuat pesanan ini dalam talian. Sila hantar mesej kepada kami di WhatsApp.",
    failPayment: "Pembayaran dalam talian tidak tersedia sekarang. Sila cuba sebentar lagi.", failInvalid: "Sila semak butiran anda dan cuba lagi.",
    failBusy: "Terlalu banyak cubaan. Sila tunggu beberapa minit dan cuba lagi.", failNetwork: "Kami tidak dapat menghubungi daftar keluar. Sila cuba lagi.",
    successTitle: "Terima kasih!", successBody: "Kami sedang mengesahkan pembayaran anda dengan penyedia pembayaran kami.", orderNumber: "Nombor pesanan",
    successHelp: "Simpan nombor ini untuk rujukan. Jika ada soalan, hantar mesej kepada kami di WhatsApp.", continueShopping: "Teruskan membeli-belah",
    cancelTitle: "Pembayaran tidak selesai", cancelBody: "Tiada caj dikenakan. Troli anda masih disimpan, jadi anda boleh cuba lagi bila-bila masa.", backToCheckout: "Kembali ke daftar keluar",
    fictional: "Semakan fiksyen sahaja", fictionalBody: "Jangan masukkan atau kongsi maklumat pelanggan sebenar dalam pratonton ini.",
    fulfilment: "Pemenuhan", fulfilmentBody: "Ambil sendiri, liputan penghantaran dan caj masih menunggu kelulusan pelanggan.",
    payment: "Pembayaran", paymentBody: "Tiada penyedia pembayaran dipilih. Pembayaran tidak tersedia dan untuk ujian sahaja.",
    noSubmission: "Semakan selesai. Pesanan dan pembayaran dinyahaktifkan.", backCart: "Kembali ke troli",
    item: "item", items: "item", itemColumn: "Produk", each: "seunit", removeItem: "Buang",
    reviewPay: "Semak dan bayar", continueToAddress: "Teruskan ke alamat penghantaran", continueToReview: "Teruskan ke semakan",
    edit: "Ubah", step: "Langkah", stepDone: "selesai", contactFor: "Butiran hubungan", deliverTo: "Hantar ke", noEmail: "Tiada e-mel diberi",
  },
} as const;
