export const cartCopy = {
  en: {
    cart: "Cart", add: "Add to cart", added: "Added to cart", unavailable: "Currently unavailable",
    title: "Your cart", eyebrow: "PRIVATE ORDER PREVIEW", intro: "Review current products and prices before the private checkout preview.",
    empty: "Your cart is ready for something delicious.", emptyBody: "Browse the collection and add a product when you are ready.", browse: "Browse products",
    quantity: "Quantity", decrease: "Decrease quantity", increase: "Increase quantity", remove: "Remove", clear: "Clear cart", clearConfirm: "Clear every item from your cart?",
    loading: "Checking current prices and availability…", error: "We could not refresh the cart.", retry: "Try again",
    noLongerAvailable: "This product is no longer available.", quantityUnavailable: "That quantity is not currently available. Reduce it to continue.",
    priceChanged: "Price updated", subtotal: "Subtotal", discount: "Discount", total: "Total", currentPricing: "Prices and availability are checked with the bakery system.",
    checkout: "Private checkout preview", checkoutDisabled: "Checkout remains unavailable outside an enabled private review.",
    checkoutTitle: "Checkout preview", checkoutIntro: "A review-only look at the future checkout. No order or payment will be created.",
    fictional: "Fictional review only", fictionalBody: "Do not enter or share real customer information in this preview.",
    orderSummary: "Order summary", fulfilment: "Fulfilment", fulfilmentBody: "Pickup, delivery coverage and charges are awaiting client approval.",
    payment: "Payment", paymentBody: "No sandbox provider has been selected. Payment is unavailable and test-only.",
    noSubmission: "Review complete — ordering and payment are disabled.", backCart: "Back to cart",
  },
  ms: {
    cart: "Troli", add: "Tambah ke troli", added: "Ditambah ke troli", unavailable: "Tidak tersedia buat masa ini",
    title: "Troli anda", eyebrow: "PRATONTON PESANAN PERIBADI", intro: "Semak produk dan harga semasa sebelum pratonton daftar keluar peribadi.",
    empty: "Troli anda sedia untuk sesuatu yang enak.", emptyBody: "Lihat koleksi dan tambah produk apabila anda bersedia.", browse: "Lihat produk",
    quantity: "Kuantiti", decrease: "Kurangkan kuantiti", increase: "Tambah kuantiti", remove: "Buang", clear: "Kosongkan troli", clearConfirm: "Kosongkan semua produk daripada troli?",
    loading: "Menyemak harga dan ketersediaan semasa…", error: "Kami tidak dapat menyegarkan troli.", retry: "Cuba lagi",
    noLongerAvailable: "Produk ini tidak lagi tersedia.", quantityUnavailable: "Kuantiti itu tidak tersedia sekarang. Kurangkan kuantiti untuk meneruskan.",
    priceChanged: "Harga dikemas kini", subtotal: "Jumlah kecil", discount: "Diskaun", total: "Jumlah", currentPricing: "Harga dan ketersediaan disemak dengan sistem bakeri.",
    checkout: "Pratonton daftar keluar peribadi", checkoutDisabled: "Daftar keluar kekal tidak tersedia di luar semakan peribadi yang diaktifkan.",
    checkoutTitle: "Pratonton daftar keluar", checkoutIntro: "Paparan semakan sahaja untuk daftar keluar akan datang. Tiada pesanan atau pembayaran akan dibuat.",
    fictional: "Semakan fiksyen sahaja", fictionalBody: "Jangan masukkan atau kongsi maklumat pelanggan sebenar dalam pratonton ini.",
    orderSummary: "Ringkasan pesanan", fulfilment: "Pemenuhan", fulfilmentBody: "Ambil sendiri, liputan penghantaran dan caj masih menunggu kelulusan pelanggan.",
    payment: "Pembayaran", paymentBody: "Tiada penyedia sandbox dipilih. Pembayaran tidak tersedia dan untuk ujian sahaja.",
    noSubmission: "Semakan selesai — pesanan dan pembayaran dinyahaktifkan.", backCart: "Kembali ke troli",
  },
} as const;
