// Draft status wording, awaiting Umar's review (ideally with a native BM reader).
export const trackingCopy = {
  en: {
    pageTitle: "Your order", findTitle: "Find my order",
    findIntro: "Enter your order number and the phone number you used at checkout.",
    orderNumber: "Order number", orderNumberHint: "Shown after payment, for example 1024.",
    phone: "Phone number", phoneHint: "The number you gave at checkout, such as 012-345 6789.",
    find: "Find order", finding: "Finding your order…",
    errorSummary: "Please check the highlighted fields.",
    fieldRequired: "Please fill this in.", orderNumberInvalid: "Enter the order number digits only.", phoneInvalid: "Use a number such as 012-345 6789, or start with + for other countries.",
    notFoundTitle: "We couldn’t find that order",
    notFound: "Check the order number and phone number. Tracking links stop working 90 days after an order is completed or cancelled. For help, message us on WhatsApp.",
    busy: "Too many attempts. Please wait a few minutes and try again.",
    failed: "We couldn’t load your order right now. Please try again shortly.",
    tryAgain: "Try again", findAnother: "Find another order",
    placedOn: "Placed", for: "For", phoneEnding: "Phone ending", timeline: "Progress", items: "Items",
    courier: "Courier", trackingNumber: "Tracking number",
    subtotal: "Subtotal", discount: "Discount", total: "Total",
    bookmark: "Bookmark this page to check your order later. Anyone with this link can see the order status, so keep it private.",
    help: "Questions about your order? Message us on WhatsApp with your order number.",
    trackOrder: "Track your order", trackHint: "Save or bookmark the tracking page to check on your order later.",
    findLink: "Lost your link? Find my order",
    stage: {
      awaitingPayment: "Awaiting payment", received: "Order received", preparing: "Being prepared",
      onTheWay: "On the way", outForDelivery: "Out for delivery", delivered: "Delivered", completed: "Completed",
      cancelled: "Cancelled", deliveryFailed: "Delivery unsuccessful, we will contact you", refunded: "Refunded",
    },
    step: {
      placed: "Order placed", paid: "Payment confirmed", preparing: "Being prepared", shipped: "On the way",
      outForDelivery: "Out for delivery", delivered: "Delivered", failed: "Delivery unsuccessful", cancelled: "Cancelled",
    },
    stepDone: "Done", stepPending: "Not yet",
  },
  ms: {
    pageTitle: "Pesanan anda", findTitle: "Cari pesanan saya",
    findIntro: "Masukkan nombor pesanan dan nombor telefon yang anda gunakan semasa checkout.",
    orderNumber: "Nombor pesanan", orderNumberHint: "Dipaparkan selepas pembayaran, contohnya 1024.",
    phone: "Nombor telefon", phoneHint: "Nombor yang anda berikan semasa checkout, seperti 012-345 6789.",
    find: "Cari pesanan", finding: "Mencari pesanan anda…",
    errorSummary: "Sila semak ruangan yang ditandakan.",
    fieldRequired: "Sila isi ruangan ini.", orderNumberInvalid: "Masukkan digit nombor pesanan sahaja.", phoneInvalid: "Gunakan nombor seperti 012-345 6789, atau mulakan dengan + untuk negara lain.",
    notFoundTitle: "Kami tidak menemui pesanan itu",
    notFound: "Semak nombor pesanan dan nombor telefon. Pautan penjejakan tamat 90 hari selepas pesanan selesai atau dibatalkan. Untuk bantuan, hantar mesej kepada kami di WhatsApp.",
    busy: "Terlalu banyak cubaan. Sila tunggu beberapa minit dan cuba lagi.",
    failed: "Kami tidak dapat memuatkan pesanan anda sekarang. Sila cuba sebentar lagi.",
    tryAgain: "Cuba lagi", findAnother: "Cari pesanan lain",
    placedOn: "Dibuat", for: "Untuk", phoneEnding: "Telefon berakhir", timeline: "Kemajuan", items: "Item",
    courier: "Kurier", trackingNumber: "Nombor penjejakan",
    subtotal: "Subjumlah", discount: "Diskaun", total: "Jumlah",
    bookmark: "Tandakan halaman ini untuk menyemak pesanan anda kemudian. Sesiapa yang mempunyai pautan ini boleh melihat status pesanan, jadi simpan secara peribadi.",
    help: "Ada soalan tentang pesanan anda? Hantar mesej kepada kami di WhatsApp bersama nombor pesanan anda.",
    trackOrder: "Jejak pesanan anda", trackHint: "Simpan atau tandakan halaman penjejakan untuk menyemak pesanan anda kemudian.",
    findLink: "Hilang pautan? Cari pesanan saya",
    stage: {
      awaitingPayment: "Menunggu pembayaran", received: "Pesanan diterima", preparing: "Sedang disediakan",
      onTheWay: "Dalam perjalanan", outForDelivery: "Sedang dihantar", delivered: "Telah dihantar", completed: "Selesai",
      cancelled: "Dibatalkan", deliveryFailed: "Penghantaran tidak berjaya, kami akan menghubungi anda", refunded: "Telah dibayar balik",
    },
    step: {
      placed: "Pesanan dibuat", paid: "Pembayaran disahkan", preparing: "Sedang disediakan", shipped: "Dalam perjalanan",
      outForDelivery: "Sedang dihantar", delivered: "Telah dihantar", failed: "Penghantaran tidak berjaya", cancelled: "Dibatalkan",
    },
    stepDone: "Selesai", stepPending: "Belum",
  },
} as const;

export type TrackingCopy = (typeof trackingCopy)["en"] | (typeof trackingCopy)["ms"];
