import api from "./axios";
import type { HandoffRule, MetaConnectionStatus, SimulatorInboundResult, SupportDraft, SupportFAQ, SupportMessage, SupportMessagingConversation, SupportRequest, SupportRequestInput, SupportRequestNote, SupportRequestPage, SupportTemplate } from "../types/support";
export interface SupportRequestFilters { search?: string; status_filter?: string; priority?: string; assigned_admin_id?: number; source?: string; has_handoff?: boolean; start_at?: string; end_at?: string; page?: number; page_size?: number; }
export const getSupportRequests=async(filters: SupportRequestFilters = {})=> (await api.get<SupportRequestPage>("/support/requests", { params: filters })).data;
export const createSupportRequest=async(data:SupportRequestInput)=>(await api.post<SupportRequest>("/support/requests",data)).data;
export const updateSupportRequest=async(id:number,data:SupportRequestInput)=>(await api.patch<SupportRequest>(`/support/requests/${id}`,data)).data;
export const deleteSupportRequest=async(id:number)=>api.delete(`/support/requests/${id}`);
export const getSupportRequestNotes=async(id:number)=> (await api.get<SupportRequestNote[]>(`/support/requests/${id}/notes`)).data;
export const createSupportRequestNote=async(id:number, content:string)=> (await api.post<SupportRequestNote>(`/support/requests/${id}/notes`, { content })).data;
export const getSupportAssignees=async()=> (await api.get<{id:number;username:string;role:"OWNER"|"STAFF"}[]>("/support/assignees")).data;
export const getFAQs=async()=> (await api.get<SupportFAQ[]>("/support/faqs")).data;
export const getTemplates=async()=> (await api.get<SupportTemplate[]>("/support/templates")).data;
export const getRules=async()=> (await api.get<HandoffRule[]>("/support/rules")).data;
export const createFAQ=async(data:Omit<SupportFAQ,"id"|"updated_at">)=>(await api.post<SupportFAQ>("/support/faqs",data)).data;
export const updateFAQ=async(id:number,data:Omit<SupportFAQ,"id"|"updated_at">)=>(await api.patch<SupportFAQ>(`/support/faqs/${id}`,data)).data;
export const deleteFAQ=async(id:number)=>api.delete(`/support/faqs/${id}`);
export const createTemplate=async(data:Omit<SupportTemplate,"id"|"updated_at">)=>(await api.post<SupportTemplate>("/support/templates",data)).data;
export const updateTemplate=async(id:number,data:Omit<SupportTemplate,"id"|"updated_at">)=>(await api.patch<SupportTemplate>(`/support/templates/${id}`,data)).data;
export const deleteTemplate=async(id:number)=>api.delete(`/support/templates/${id}`);
export const createRule=async(data:Omit<HandoffRule,"id"|"updated_at">)=>(await api.post<HandoffRule>("/support/rules",data)).data;
export const updateRule=async(id:number,data:Omit<HandoffRule,"id"|"updated_at">)=>(await api.patch<HandoffRule>(`/support/rules/${id}`,data)).data;
export const deleteRule=async(id:number)=>api.delete(`/support/rules/${id}`);
export const createSupportDraft=async(data:{message:string;language:"AUTO"|"EN"|"MS";support_request_id?:number})=>(await api.post<SupportDraft>("/support/copilot/draft",data)).data;
export const simulateInboundMessage=async(data:{message_id:string;conversation_id:string;sender_reference:string;message:string;language:"AUTO"|"EN"|"MS"})=>(await api.post<SimulatorInboundResult>("/support/simulator/inbound",data)).data;
export const getMetaConnectionStatus=async()=> (await api.get<MetaConnectionStatus>("/support/meta/status")).data;
export const getSupportMessagingConversation=async(id:number)=> (await api.get<SupportMessagingConversation | null>(`/support/requests/${id}/messaging-conversation`)).data;
export const getSupportMessages=async(id:number)=> (await api.get<SupportMessage[]>(`/support/requests/${id}/messages`)).data;
export const claimSupportConversation=async(id:number)=> (await api.post<SupportRequest>(`/support/requests/${id}/claim`)).data;
export const returnSupportConversationToAi=async(id:number)=> (await api.post<SupportRequest>(`/support/requests/${id}/return-to-ai`)).data;
export const requestHumanTakeover=async(id:number)=> (await api.post<SupportRequest>(`/support/requests/${id}/request-human-takeover`)).data;
export const sendSimulatedDashboardReply=async(id:number, content:string)=> (await api.post<SupportMessage>(`/support/requests/${id}/dashboard-replies`, { content })).data;
export const getWhatsAppLink=async(id:number)=> (await api.get<{url:string}>(`/support/requests/${id}/whatsapp-link`)).data;
