import { ActionIcon, Badge, Button, Group, Modal, Stack, Switch, Text, TextInput, Textarea, Tooltip } from "@mantine/core";
import { useForm } from "@mantine/form";
import { notifications } from "@mantine/notifications";
import { modals } from "@mantine/modals";
import { IconEdit, IconPlus } from "@tabler/icons-react";
import type { ColumnDef } from "@tanstack/react-table";
import { useCallback, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { createSupplier, getSuppliers, updateSupplier } from "../../api/suppliers";
import { getApiError } from "../../api/errors";
import { DataTable } from "../../components/common/DataTable";
import PageHeader from "../../components/common/PageHeader";
import type { Supplier } from "../../types/supplier";

const blank = { name: "", contact_name: "", phone: "", email: "", note: "", is_active: true };
export default function Suppliers() {
  const queryClient = useQueryClient(); const { data = [], isLoading } = useQuery({ queryKey: ["suppliers"], queryFn: getSuppliers }); const [editing, setEditing] = useState<Supplier | null>(null); const [opened, setOpened] = useState(false);
  const form = useForm({ initialValues: blank, validate: { name: (value) => value.trim().length > 1 ? null : "Enter supplier name" } });
  const save = useMutation({ mutationFn: () => { const values = { ...form.values, name: form.values.name.trim(), contact_name: form.values.contact_name.trim() || null, phone: form.values.phone.trim() || null, email: form.values.email.trim() || null, note: form.values.note.trim() || null }; return editing ? updateSupplier(editing.id, values) : createSupplier(values); }, onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["suppliers"] }); notifications.show({ title: "Supplier saved", message: "Supplier details were updated.", color: "green" }); setOpened(false); }, onError: (error) => { const item = getApiError(error); form.setErrors(item.fieldErrors); notifications.show({ title: "Unable to save supplier", message: item.message, color: "red" }); } });
  const edit = useCallback((item: Supplier) => { setEditing(item); form.setValues({ name: item.name, contact_name: item.contact_name ?? "", phone: item.phone ?? "", email: item.email ?? "", note: item.note ?? "", is_active: item.is_active }); form.resetDirty(); setOpened(true); }, [form]);
  const columns = useMemo<ColumnDef<Supplier, unknown>[]>(() => [{ accessorKey: "name", header: "Supplier", cell: ({ row }) => <Text fw={600}>{row.original.name}</Text> }, { accessorKey: "contact_name", header: "Contact" }, { accessorKey: "phone", header: "Phone" }, { accessorKey: "is_active", header: "Status", cell: ({ row }) => <Badge color={row.original.is_active ? "green" : "gray"} variant="light">{row.original.is_active ? "Active" : "Inactive"}</Badge> }, { id: "actions", header: "Actions", enableSorting: false, cell: ({ row }) => <Tooltip label="Edit supplier"><ActionIcon variant="light" aria-label="Edit supplier" onClick={() => edit(row.original)}><IconEdit size={16} /></ActionIcon></Tooltip> }], [edit]);
  const openCreate = () => { setEditing(null); form.setValues(blank); form.resetDirty(blank); setOpened(true); };
  return <><PageHeader title="Suppliers" description="Manage suppliers used for stock receipts. Supplier history is retained when an account is inactive." action={<Button leftSection={<IconPlus size={16} />} onClick={openCreate}>Add supplier</Button>} /><DataTable data={data} columns={columns} loading={isLoading} searchPlaceholder="Search suppliers..." emptyMessage="No suppliers yet." /><Modal opened={opened} onClose={() => { if(save.isPending)return; if(form.isDirty())modals.openConfirmModal({title:"Discard supplier changes?",children:<Text>Your changes have not been saved.</Text>,labels:{confirm:"Discard",cancel:"Keep editing"},onConfirm:()=>setOpened(false)});else setOpened(false); }} title={editing ? "Edit supplier" : "Add supplier"} centered><form onSubmit={form.onSubmit(() => save.mutate())}><Stack><TextInput label="Supplier name" withAsterisk {...form.getInputProps("name")} /><TextInput label="Contact name" {...form.getInputProps("contact_name")} /><TextInput label="Phone" {...form.getInputProps("phone")} /><TextInput label="Email" {...form.getInputProps("email")} /><Textarea label="Internal note" {...form.getInputProps("note")} />{editing ? <Switch label="Supplier is active" {...form.getInputProps("is_active", { type: "checkbox" })} /> : null}<Group justify="flex-end"><Button variant="default" disabled={save.isPending} onClick={() => {if(form.isDirty())modals.openConfirmModal({title:"Discard supplier changes?",children:<Text>Your changes have not been saved.</Text>,labels:{confirm:"Discard",cancel:"Keep editing"},onConfirm:()=>setOpened(false)});else setOpened(false);}}>Cancel</Button><Button type="submit" loading={save.isPending}>Save supplier</Button></Group></Stack></form></Modal></>;
}
