ORDER_STATUS = [
    "PENDING",
    "PROCESSING",
    "SHIPPED",
    "COMPLETED",
    "CANCELLED",
]

PAYMENT_STATUS = [
    "UNPAID",
    "PAID",
    "FAILED",
    "REFUNDED",
]

ORDER_STATUS_TRANSITIONS = {
    "PENDING": {"PROCESSING"},
    "PROCESSING": {"SHIPPED"},
    "SHIPPED": {"COMPLETED"},
    "COMPLETED": set(),
    "CANCELLED": set(),
}
